const shop = [
  {
    id: 0,
    name: "Ramen",
    manufacturer: "Akasaka",
    price: 29.99,
    instock: 1000000000,
    description: "łagodna zupa z kurczakiem, pierożkami, warzywami i jajkiem",
    imgSrc: "food/ramen.jpg",
    numberofUnits: 1,
    quantity: 1,
  },
  {
    id: 1,
    name: "Kurczak BBQ",
    manufacturer: "Starbucks",
    price: 24.99,
    instock: 1000000000,
    description: "stripsy z kurczaka połączone z sosem BBQ",
    imgSrc: "food/sandwiches.jpg",
    numberofUnits: 1,
    quantity: 1,
  },
  {
    id: 2,
    name: "Pierożki Gyoza",
    manufacturer: "Akasaka",
    price: 19.99,
    instock: 1000000000,
    description: "gotowane na parze pierożki dim sum z tempeh i warzywami",
    imgSrc: "food/gyoza.jpg",
    numberofUnits: 1,
    quantity: 1,
  },
  {
    id: 3,
    name: "Spaghetti bolognese",
    manufacturer: "Italiano",
    price: 25.99,
    instock: 1000000000,
    description:
      "sos pomidorowo-warzywny z duszoną mieloną wołowiną z dodatkiem wieprzowiny",
    imgSrc: "food/spaghetti-bolognese.jpg",
    numberofUnits: 1,
    quantity: 1,
  },
  {
    id: 4,
    name: "Sushi",
    manufacturer: "Akasaka",
    price: 13.99,
    instock: 1000000000,
    description:
      "3 szt nigiri maślana, 3 szt nigiri tuńczyk, 3 szt nigiri łosoś, 6 szt maki, 5 szt california łosoś",
    imgSrc: "food/sushi.jpg",
    numberofUnits: 1,
    quantity: 1,
  },
  {
    id: 5,
    name: "Teriyaki",
    manufacturer: "Akasaka",
    price: 16.99,
    instock: 1000000000,
    description:
      "chrupiące kawałki kurczaka w pomarańczowym sosie teriyaki, podane z ryżem",
    imgSrc: "food/teriyaki.jpg",
    numberofUnits: 1,
    quantity: 1,
  },
  {
    id: 6,
    name: "Szarlotka",
    manufacturer: "Starbucks",
    price: 18.99,
    instock: 1000000000,
    description: "szarlotka na ciepło z lodami waniliowymi",
    imgSrc: "food/apple-pie.jpg",
    numberofUnits: 1,
    quantity: 1,
  },
  {
    id: 7,
    name: "Pizza Grecka",
    manufacturer: "Italiano",
    price: 12.99,
    instock: 1000000000,
    description:
      "sos biały, ser mozzarella, oliwki czarne, ser śródziemnomorski",
    imgSrc: "food/pizza-grecka.jpg",
    numberofUnits: 1,
    quantity: 1,
  },
  {
    id: 8,
    name: "Veggie burger",
    manufacturer: "Mc Donalds",
    price: 10.99,
    instock: 1000000000,
    description:
      "150g wege kotleta na bazie kaszy jaglanej z warzywami i ziarnami sezamu oraz słonecznika, warzywa, sos do wyboru",
    imgSrc: "food/veggie-burger.jpg",
    numberofUnits: 1,
    quantity: 1,
  },
  {
    id: 9,
    name: "Frytki",
    manufacturer: "Mc Donalds",
    price: 5.99,
    instock: 1000000000,
    description: "porcja 170g frytek z ziemniaków",
    imgSrc: "food/potato-sticks.jpg",
    numberofUnits: 1,
    quantity: 1,
  },
  {
    id: 10,
    name: "Burrito",
    manufacturer: "Mc Donalds",
    price: 15.99,
    instock: 1000000000,
    description:
      "z kurczakiem, pastą z fasoli, salsą z jalapeño i sałatą, zawinięte w pszenną tortillę",
    imgSrc: "food/burritos.jpg",
    numberofUnits: 1,
    quantity: 1,
  },
  {
    id: 11,
    name: "Frappuccino",
    manufacturer: "Starbucks",
    price: 10.99,
    instock: 1000000000,
    description:
      "syrop o smaku karmelowym, połączony z kawą i mlekiem, całość zblendowana z lodem",
    imgSrc: "food/frappuccino.jpg",
    numberofUnits: 1,
    quantity: 1,
  },
];
